      <div class="clear"> lalala </div>

    </div>

    <div id="footer">

      &copy; Andrew Mouat 2014. <br />
	Sadly, this is not a real business website; Just a student-made website for an assignment. <br />
	As such, I'd like to thank my friends and tutors (tutorial and lab classes) who helped me get it done. <br />
	Much thanks go to Google, <a href="www.php.net"> PHP.net </a>, <a href="http://www.tizag.com/"> Tizag </a>, <a href="http://regexpal.com/"> RegexPal </a>, 
	and <a href="http://writecodeonline.com/php/"> WriteCodeOnline </a>. <br />
	Lastly and leastly, I'd like to thank anyone who was responsible for teaching me web programming skills but were more interested in sports and irrelevant topics.

    </div>

  </body>

</html>